[build]
  functions = "netlify/functions"
  publish = "."

# API redirects (must come before catch-all)
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/videos"
  to = "/.netlify/functions/videos"
  status = 200

[[redirects]]
  from = "/api/videos/*"
  to = "/.netlify/functions/videos-id/:splat"
  status = 200

[[redirects]]
  from = "/api/export"
  to = "/.netlify/functions/export"
  status = 200

[[redirects]]
  from = "/api/import"
  to = "/.netlify/functions/import"
  status = 200

[[redirects]]
  from = "/api/merge"
  to = "/.netlify/functions/merge"
  status = 200

[[redirects]]
  from = "/api/debug"
  to = "/.netlify/functions/debug"
  status = 200

# Catch-all redirect for SPA (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
